### ISSUE TITLE
Users might need to specify compiler explicitly depending on CMake configuration

### ISSUE THREAD

**Issue by warrickball** [carlislewishard/swiftest#10]
I've just tried building Swiftest on our cluster, which uses Environment Modules, and CMake (which I had to load as a module too, incidentally) always finds GCC instead of ifort. I had to manually set this in the pre-build step with
```
$ cmake .. -DCMAKE_Fortran_COMPILER=$(which ifort)
```
You may want to document this.

The build did succeed with these modules, by the way:
```
$ module list

Currently Loaded Modules:
  1) bb-variables/live         14) bluebear/live                    27) libpciaccess/0.16-GCCcore-10.2.0
  2) slurm-helpers/live        15) GCCcore/10.2.0                   28) hwloc/2.2.0-GCCcore-10.2.0
  3) openmpi-env/live          16) ncurses/6.2-GCCcore-10.2.0       29) libevent/2.1.12-GCCcore-10.2.0
  4) bear-licences/live        17) zlib/1.2.11-GCCcore-10.2.0       30) UCX/1.9.0-GCCcore-10.2.0
  5) bb-singularity-conf/live  18) bzip2/1.0.8-GCCcore-10.2.0       31) libfabric/1.11.0-GCCcore-10.2.0
  6) bear-apps/2018b/live      19) cURL/7.72.0-GCCcore-10.2.0       32) OpenMPI/4.0.5-iccifort-2020.4.304
  7) bear-apps/2019a/live      20) libarchive/3.4.3-GCCcore-10.2.0  33) iompi/2020b
  8) bear-apps/2019b/live      21) CMake/3.18.4-GCCcore-10.2.0      34) HDF5/1.10.7-iompi-2020b
  9) bear-apps/handbuilt/2020  22) binutils/2.35-GCCcore-10.2.0     35) Szip/2.1.1-GCCcore-10.2.0
 10) bear-apps/2020a/live      23) iccifort/2020.4.304              36) netCDF/4.7.4-iompi-2020b
 11) bear-apps/2020b/live      24) numactl/2.0.13-GCCcore-10.2.0    37) netCDF-Fortran/4.5.3-iompi-2020b
 12) bear-apps/2021a/live      25) XZ/5.2.5-GCCcore-10.2.0
 13) bear-apps/auto-load       26) libxml2/2.9.10-GCCcore-10.2.0
```
I explicitly loaded `netCDF-Fortran` and `CMake` and the rest are dependencies.

**Comment by warrickball** [comment]
> ... CMake (which I had to load as a module too, incidentally) ...

Just wanted to flag that having to load a CMake module (rather than use the OS version) is a local cluster configuration issue, not a Swiftest issue and not likely to be an issue on other systems.

**Comment by carlislewishard** [comment]
That's interesting and not an issue I have come across. I'm curious if any of the other reviewers had this issue. I will add in a comment to the README that mentions this, just in case others have issues as well.

**Comment by warrickball** [comment]
I don't think any of the reviewers have tried to build with `ifort`. It's a low-priority issue, since I was able to work around it. If possible, you might want to try to find someone with access to `ifort` and ask how the Swiftest build goes for them.

**Comment by carlislewishard** [comment]
We actually exclusively use ifort here at Purdue. So far we haven't run into this issue when getting new users up and running, but like I have learned throughout this review process, every configuration is different and what works for us most likely won't work for anyone else!

**Comment by profminton** [comment]
The way the Purdue RCAC cluster system is configured you can only have either gcc or intel compilers installed. If you load the intel module, it automatically unloads the gcc module and vice versa. So we never ran into this before.

**Comment by warrickball** [comment]
Fair enough. I don't know how typical it is for clusters to have the sort of GCC/ifort mix that we do. I guess it means the admins only have to build one (GCC-based) toolchain up to the first point that they decide to start building with both ifort and GCC. I leave it to you whether or not you'd like to document it for now (and close this). If I find evidence that this is common, I'll mention it here.

**Comment by profminton** [comment]
I've added additional documentation to the README that specifies how to set the path to the compiler via the CMake options `-DCMAKE_Fortran_COMPILER`.
