### ISSUE TITLE
Disabling output

### ISSUE THREAD

**Issue by hannorein** [carlislewishard/swiftest#16]
I'm probably missing something, but I can't seem to run a simulation without generating a large data.nc file. Regardless of what I set for dump_cadence or istep_out, I always end up with at least a 57MB file. I don't think this affects runtime very much so maybe this is just one output? But there are only 9 particles in the simulation so why is it so large?

**Comment by profminton** [comment]
The initial conditions are always written first before the run starts.

With the NetCDF file format there are a couple of dimensions that are set as “unlimited” (namely the time and name dimensions). It allocates a certain size for those dimensions and then resizes if it grows beyond that. 

Despite the many advantages that NetCDF/HDF offers, especially for ease of post-processing, it was designed for dense gridded data used by climate modelers, and support for sparse data is not great, especially with big SyMBA+Fraggle runs where particles come and go constantly.
