### ISSUE TITLE
Disable OpenMP

### ISSUE THREAD

**Issue by hannorein** [carlislewishard/swiftest#17]
(Sorry for the flood of issues. But I can finally run the code (yay) and I thought this might be easiest to keep track of things.)

I can set the environment variable OMP_NUM_THREADS to 1 to only run on 1 core. But it would be nice to simply disable OpenMP entirely when compiling swiftest. Is that possible?

**Comment by profminton** [comment]
Yes this is possible. Just pass the argument -DUSE_OPENMP=OFF when building with cmake.

**Comment by hannorein** [comment]
That works. Thank you!
