### ISSUE TITLE
Expected performance of `whm_gr_test`

### ISSUE THREAD

**Issue by warrickball** [carlislewishard/swiftest#25]
I just installed Swiftest using `python3 -m pip install --user` on my local HPC system (thanks for simplifying this so much), after also loading modules for NumPy, SciPy, Astropy, HDF5 and netCDF. To see if Swiftest was working, I tried downloading `whm_gr_test.py` and running it:
```
$ wget https://raw.githubusercontent.com/carlislewishard/swiftest/master/examples/whm_gr_test/whm_gr_test.py
$ python3 whm_gr_test.py
...
Mean precession rate for Mercury long. peri. (arcsec/100 y)                                                                                                                                                                                  
JPL Horizons         : 570.6996092748061                                                                                                                                                                       
Swiftest No GR       : 1776.1010725976398
Swiftest GR          : 1818.9516232474375
Obs - Swiftest GR    : -1248.2520139726316
Obs - Swiftest No GR : -1205.401463322834
```
From my limited knowledge of gravitational dynamics, I thought perhaps `Obs - Swiftest GR` would be closer to zero. Here's the plot generated in `whm_gr_mercury_precession.png`:
![whm_gr_mercury_precession](https://github.com/carlislewishard/swiftest/assets/20858744/5ebefb3a-0f2d-4713-9aad-19f5c6a73587)

Is this expected behaviour? Or should the prediction match the observations better? Either way, it would be useful to add some simple (and perhaps quite loose) checks that the test results are acceptable, or if something is wrong and users should report a bug.

<details>
  <summary>List of modules</summary>

```
 ...
 16) GCCcore/10.3.0
 17) zlib/1.2.11-GCCcore-10.3.0
 18) binutils/2.36.1-GCCcore-10.3.0
 19) GCC/10.3.0
 20) numactl/2.0.14-GCCcore-10.3.0
 21) XZ/5.2.5-GCCcore-10.3.0
 22) libxml2/2.9.10-GCCcore-10.3.0
 23) libpciaccess/0.16-GCCcore-10.3.0
 24) hwloc/2.4.1-GCCcore-10.3.0
 25) OpenSSL/1.1
 26) libevent/2.1.12-GCCcore-10.3.0
 27) UCX/1.10.0-GCCcore-10.3.0
 28) libfabric/1.12.1-GCCcore-10.3.0
 29) PMIx/3.2.3-GCCcore-10.3.0
 30) OpenMPI/4.1.1-GCC-10.3.0
 31) OpenBLAS/0.3.15-GCC-10.3.0
 32) FlexiBLAS/3.0.4-GCC-10.3.0
 33) gompi/2021a
 34) FFTW/3.3.9-gompi-2021a
 35) ScaLAPACK/2.1.0-gompi-2021a-fb
 36) foss/2021a
 37) bzip2/1.0.8-GCCcore-10.3.0
 38) libreadline/8.1-GCCcore-10.3.0
 39) ncurses/6.2-GCCcore-10.3.0
 40) Tcl/8.6.11-GCCcore-10.3.0
 41) SQLite/3.35.4-GCCcore-10.3.0
 42) GMP/6.2.1-GCCcore-10.3.0
 43) libffi/3.3-GCCcore-10.3.0
 44) Python/3.9.5-GCCcore-10.3.0
 45) pybind11/2.6.2-GCCcore-10.3.0
 46) SciPy-bundle/2021.05-foss-2021a
 47) libyaml/0.2.5-GCCcore-10.3.0
 48) PyYAML/5.4.1-GCCcore-10.3.0
 49) astropy/5.0.4-foss-2021a
 50) Szip/2.1.1-GCCcore-10.3.0
 51) HDF5/1.10.7-gompi-2021a
 52) cURL/7.76.0-GCCcore-10.3.0
 53) netCDF/4.8.0-gompi-2021a
```
</details>

**Comment by profminton** [comment]
Thanks for this. That is quite unexpected. I've been meaning to add more thorough tests to the automatic test suite, and this would be a good one to add. 

It appears to me that something is being miscalculated in the JPL Horizons solution data, possibly as a result of some changes I made recently to how the Horizons data is parsed.

**Comment by profminton** [comment]
Well, the precession rate of Mercury should be about 570 "/100 y, so it's not the JPL Horizons data that is the issue, it's something else (and shame on me for blaming the data and not the model. You'd think I'd have learned by now not to do that).

**Comment by profminton** [comment]
I have identified the issue, and it was indeed related to the new JPL Horizons query code that Swiftest uses to generate initial conditions for known solar system bodies. 

For some context, earlier in the summer I had overhauled the function that pulls ephemeris and physical property data from the JPL Horizons service. The new functionality allows us to initialize just about any body in their system by name (planets, satellites, asteroids, KBOs, etc), and extract whatever physical properties (radius, G*Mass, rotation state, etc) are available by parsing the raw output provided by the Horizons service via the astroquery jplhorizons package.  

However, I when parsing the G*Mass values, I introduced two mistakes that lead to getting _almost_ the correct value when using standard units of AU/y, which is what I had been testing with. I corrected this mistake, and am now in the process of rebuilding the wheels. 

This is the output of the `whm_gr_test` after the fix: 
```
Mean precession rate for Mercury long. peri. (arcsec/100 y)
JPL Horizons         : 570.6996092748061
Swiftest No GR       : 527.6919976632365
Swiftest GR          : 570.6301267462231
Obs - Swiftest GR    : 0.06948252858275111
Obs - Swiftest No GR : 43.00761161156938
```

**Comment by warrickball** [comment]
Great!

> `Obs - Swiftest GR    : 0.06948252858275111`

This is more like what I expected, given my basic historical knowledge of GR being important for correctly computing the precession of Mercury.

> I've been meaning to add more thorough tests to the automatic test suite, and this would be a good one to add.

Absolutely: bugfixes are great for writing tests to make sure that the same error doesn't turn up again (i.e. you don't get a "regression").

I'll watch out for new wheels and confirm the fix when I can.

**Comment by profminton** [comment]
The new wheels have been uploaded to PyPI. Both `whm_gr_test` and `helio_gr_test` appear to be working correctly on all the machines I've tried it on.

**Comment by warrickball** [comment]
I just checked `whm_gr_test` and it worked for me, so I think this is resolved. Thanks!
