### ISSUE TITLE
Issue compiling with GNU fortran compiler

### ISSUE THREAD

**Issue by mikegrudic** [carlislewishard/swiftest#3]
Howdy!

I am trying out the code for the JOSS submission. Echoing Hanno's experience, I was unable to build it due to issues getting NetCDF-Fotran linked up correctly in a couple different HPC environments (NAS Aitken and TACC Frontera), but eventually built NetCDF from scratch on my home Linux (Pop! OS) machine and got that bit to work - with one modification. Trying to compile with gfortran 11.3.0 gives the following error:

```
/home/mike/code/swiftest/src/misc/solver_module.f90:352:21:

  352 |             if (.not.RootBracketed(FA,FB)) then
      |                     1
Error: Operand of .not. operator at (1) is INTEGER(4)
/home/mike/code/swiftest/src/misc/solver_module.f90:358:27:

  358 |                   if (.not.RootBracketed(FC,FB)) then
      |                           1
Error: Operand of .not. operator at (1) is INTEGER(4)
 
```

I think the issue here is that gfortran does not support implicit conversion from int to logical inside if conditions. I modified RootBracketed to return logical and it compiled and ran fine.

**Comment by carlislewishard** [comment]
Mike - Great to hear that you were able to compile and run the code! Out of curiosity, were you able to create a set of initial conditions using the Python package or did you run one of the example scripts? 

Thanks for the tip on gfortran. I will have to look into if this is something that has changed between versions or something that we somehow missed. The Purdue cluster system only has up to version gcc/10.2.0, so it is possible that things have changed between that version and 11.3.0.

**Comment by mikegrudic** [comment]
> Out of curiosity, were you able to create a set of initial conditions using the Python package or did you run one of the example scripts?

So far, I have installed the python package, run the IC generator for examples/BasicSimualtion, and run the simulation by directly running ./swiftest_driver.

**Comment by profminton** [comment]
Hi Mike. Thanks for the feedback. Are you on the master branch by chance? I believe I actually caught that bug just after we submitted the code for review at JOSS, and so the fix I implemented is still in the debug branch awaiting a PR review. I have made a number of improvements and bug fixes in the debug branch while helping Hanno out, but they are all currently still in debug. I'm not sure what the best practice is for this, whether to do a code review ourselves on the PR and merge into master, or have you checkout the debug branch until the review is complete. Let me know what you prefer.

**Comment by profminton** [comment]
Another thing to look at in the debug branch is the Dockerfile, which serves as a useful guide for how to build the dependencies (NetCDF-Fortran/C and HDF5) from scratch as static libraries from a clean install (Ubuntu, as that's what the Intel HPC Docker uses).

**Comment by mikegrudic** [comment]
Yes this is using the master branch. The debug branch sounds pretty nifty, I'll at least check that it compiles in my environment and let you know if there are any issues.
