### ISSUE TITLE
License

### ISSUE THREAD

**Issue by hannorein** [carlislewishard/swiftest#4]
I see the license statement at the end of the readme file, but I don't think the actual license is included in the repository. Did I miss it? If not can you include a plain text copy? 

#openjournals/joss-reviews/issues/5409

**Comment by carlislewishard** [comment]
Hi Hanno, you can find the license in the topmost directory as COPYING.txt per the GNU Public License. Let me know if you have issues finding it.

**Comment by hannorein** [comment]
Ah. Of course. Sorry. I was excepting LICENSE.txt, but I guess COPYING.txt is the recommended name.
