### ISSUE TITLE
Installation [Linux Fedora 38 / GCC 13.1.1] 

### ISSUE THREAD

**Issue by aatrani** [carlislewishard/swiftest#7]
Even with the correct libraries installed, the code would not compile by default.
Here are the actions I had to make to make it compile. Consider adjusting the cmake files and/or adding info to the readme 

1. Missing netcdf error, despite cmake configured successfully
```
swiftest/src/collision/collision_io.f90:130:11:

  130 |       use netcdf
      |           1
Fatal Error: Cannot open module file ‘netcdf.mod’ for reading at (1): No such file or directory
compilation terminated.
```
Solution:
Add the cmake flags `-DCMAKE_Fortran_FLAGS=-I/usr/lib64/gfortran/modules/`, where netcdf.mod is located on my system

2. Line truncation error
```
swiftest/src/collision/collision_module.f90:39:132:

   39 |    character(len=NAMELEN),dimension(5), parameter :: REGIME_NAMES = [REGIME_NAME_MERGE, REGIME_NAME_DISRUPTION, REGIME_NAME_SUPERCATASTROPHIC, REGIME_NAME_GRAZE_AND_MERGE, REGIME_NAME_HIT_AND_RUN]
      |                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
```
Solution: 
Add the cmake flags `-DCMAKE_Fortran_FLAGS=-ffree-line-length-512` . Consider adding this by default into the cmake if GCC is selected as compiler, or fix the length of the offending line(s)

**Comment by carlislewishard** [comment]
Thanks for the update, I'm glad that you were able to get it to compile after a few tweaks. I also saw that you made a change to the README, so thank you for your contribution. I believe that change should address your first issue, is that correct? I will make that change to the cmake file that should fix your second issue. Thank you for your suggestions and let me know if you come across any other issues as you continue.

**Comment by aatrani** [comment]
> I also saw that you made a change to the README, so thank you for your contribution. I believe that change should address your first issue, is that correct?

Initially I thought so, but actually is unrelated, I had to use another cmake command line eventually! I'll continue posting issues/solutions as I find them. Cheers

**Comment by warrickball** [comment]
Just wanted to flag that I also ran into this issue on Fedora 37 & GCC 12.3.1. I used the same solution of combining the two flags @aatrani suggested, i.e.
```
$ cmake -DCMAKE_Fortran_FLAGS="-I/usr/lib64/gfortran/modules/ -ffree-line-length-512" ..
$ make
...
[100%] Linking Fortran executable swiftest_driver
[100%] Built target swiftest_driver
$
```

**Comment by carlislewishard** [comment]
Thanks for the feedback. I added these flags to the README.

**Comment by profminton** [comment]
I set the `-ffree-line-length-512` as a default flag. As for the additional dependency, which is system-specific, I added that in the new table that shows example CMake options.
